/* eslint-disable radix */
/* eslint-disable no-use-before-define */
exports.StateName = (pincode) => StateName(pincode);

function StateName(pincode) {
  const twodigit = parseInt(pincode / 10000);
  const threedigit = parseInt(pincode / 1000);
  switch (threedigit) {
    case 396:
      return 'DadraandNagarHaveliandDamanandDiu';
    case 403:
      return 'Goa';
    case 744:
      return 'AndamanandNicobarIslands';
    case 682:
      return 'Lakshadweep';
    default:
  }
  switch (twodigit) {
    case 11:
      return 'Delhi';
    case 12:
      return 'Haryana';
    case 13:
      return 'Haryana';
    case 14:
      return 'Punjab';
    case 15:
      return 'Punjab';
    case 16:
      return 'Chandigarh';
    case 17:
      return 'HimachalPradesh';
    case 18:
      return 'JammuandKashmir';
    case 19:
      return 'JammuandKashmir';
    case 20:
      return 'UttarPradeshandUttarakhand';
    case 21:
      return 'UttarPradeshandUttarakhand';
    case 22:
      return 'UttarPradeshandUttarakhand';
    case 23:
      return 'UttarPradeshandUttarakhand';
    case 24:
      return 'UttarPradeshandUttarakhand';
    case 25:
      return 'UttarPradeshandUttarakhand';
    case 26:
      return 'UttarPradeshandUttarakhand';
    case 27:
      return 'UttarPradeshandUttarakhand';
    case 28:
      return 'UttarPradeshandUttarakhand';
    case 30:
      return 'Punjab';
    case 31:
      return 'Punjab';
    case 32:
      return 'Punjab';
    case 33:
      return 'Punjab';
    case 34:
      return 'Punjab';
    case 36:
      return 'Gujarat';
    case 37:
      return 'Gujarat';
    case 38:
      return 'Gujarat';
    case 39:
      return 'Gujarat';
    case 40:
      return 'Maharashtra';
    case 41:
      return 'Maharashtra';
    case 42:
      return 'Maharashtra';
    case 43:
      return 'Maharashtra';
    case 44:
      return 'Maharashtra';
    case 45:
      return 'MadhyaPradesh';
    case 46:
      return 'MadhyaPradesh';
    case 47:
      return 'MadhyaPradesh';
    case 48:
      return 'MadhyaPradesh';
    case 49:
      return 'Chattisgarh';
    case 50:
      return 'Telangana';
    case 51:
      return 'AndhraPradesh';
    case 52:
      return 'AndhraPradesh';
    case 53:
      return 'AndhraPradesh';
    case 56:
      return 'Karnataka';
    case 57:
      return 'Karnataka';
    case 58:
      return 'Karnataka';
    case 59:
      return 'Karnataka';
    case 60:
      return 'TamilNadu';
    case 61:
      return 'TamilNadu';
    case 62:
      return 'TamilNadu';
    case 63:
      return 'TamilNadu';
    case 64:
      return 'TamilNadu';
    case 65:
      return 'TamilNadu';
    case 66:
      return 'TamilNadu';
    case 67:
      return 'Kerala';
    case 68:
      return 'Kerala';
    case 69:
      return 'Kerala';
    case 70:
      return 'WestBengal';
    case 71:
      return 'WestBengal';
    case 72:
      return 'WestBengal';
    case 73:
      return 'WestBengal';
    case 74:
      return 'WestBengal';
    case 75:
      return 'Odisha';
    case 76:
      return 'Odisha';
    case 77:
      return 'Odisha';
    case 79:
      return 'NorthEastern';
    case 78:
      return 'Assam';
    case 80:
      return 'BiharandJaharkhand';
    case 81:
      return 'BiharandJaharkhand';
    case 82:
      return 'BiharandJaharkhand';
    case 83:
      return 'BiharandJaharkhand';
    case 84:
      return 'BiharandJaharkhand';
    case 85:
      return 'BiharandJaharkhand';
    default:
      return 'WrongPinCode';
  }
}
